module.exports = {
  words: [
    'cheese',
    'sausage',
    'pepperoni',
    'buffalo',
    'mozzarella',
    'calzone',
    'Chicago style',
    'deep-dish',
    'margherita',
    'marinara',
    'New York style',
    'thin crust',
    'thick crust',
    'pan pizza',
    'pizza cutter',
    'Sicilian',
    'pie',
    'slice',
    'cheesy',
    'crust',
    'dough',
    'pizzeria',
    'crushed red pepper',
    'parmesan cheese',
    'piece',
    'sauce',
    'brick-oven',
    'tomato sauce',
    'wood-fired oven',
    'leopard spotting',
    'pie in the sky',
    'mushroom',
    'onion',
    'garlic',
    'basil',
    'tomato',
    'pineapple',
    'olives',
    'parmigiano-reggiano',
    'oregano',
    'peperoncini',
    'banana peppers',
    'garlic butter'
  ]
}
